// VIP / rakeback tier ladder. Tier is determined by lifetime wagered (USDT).
// Higher tiers earn a larger share of the house fee back as rakeback.
//
// Rakeback is *not* the same as referral earnings:
//   - Referral earnings = % of fees generated by users you refer
//   - Rakeback           = % of fees generated by YOU yourself
//
// For MVP we compute "earned this week" on-the-fly from house_fee_ledger +
// crash_bets.fee_cents + instant_game_bets stake×house-edge. A separate
// weekly cron will move "earned" -> balance every Monday (deferred to a
// later phase).

export interface VipTier {
  id: 'bronze' | 'silver' | 'gold' | 'platinum' | 'diamond' | 'obsidian';
  name: string;
  emoji: string;
  minWageredUsdt: number;
  rakebackBps: number;            // basis points of house fee returned
  color: string;
  perks: string[];
}

export const VIP_TIERS: VipTier[] = [
  { id: 'bronze',   name: 'Bronze',   emoji: '🥉', minWageredUsdt: 0,        rakebackBps: 100,
    color: '#A56A3A',
    perks: ['1% rakeback on house fees', 'Daily login bonus', 'Welcome bonus 3 USDT'] },
  { id: 'silver',   name: 'Silver',   emoji: '🥈', minWageredUsdt: 500,      rakebackBps: 200,
    color: '#B7C6D3',
    perks: ['2% rakeback on house fees', 'Higher daily withdraw limit', 'Priority support'] },
  { id: 'gold',     name: 'Gold',     emoji: '🥇', minWageredUsdt: 5_000,    rakebackBps: 300,
    color: '#E8A53C',
    perks: ['3% rakeback', 'Weekly cashback boost', 'Beta access to new games'] },
  { id: 'platinum', name: 'Platinum', emoji: '💎', minWageredUsdt: 50_000,   rakebackBps: 500,
    color: '#0E7C66',
    perks: ['5% rakeback', 'Personal account manager', 'Custom bet limits'] },
  { id: 'diamond',  name: 'Diamond',  emoji: '🔷', minWageredUsdt: 250_000,  rakebackBps: 700,
    color: '#2E8FC9',
    perks: ['7% rakeback', 'Monthly USDT bonus', 'VIP-only markets'] },
  { id: 'obsidian', name: 'Obsidian', emoji: '⬛', minWageredUsdt: 1_000_000, rakebackBps: 1000,
    color: '#0B1F2E',
    perks: ['10% rakeback', 'Concierge desk', 'Bespoke withdrawal lanes'] },
];

export function tierForWagered(lifetimeWageredUsdt: number): VipTier {
  let pick = VIP_TIERS[0];
  for (const t of VIP_TIERS) {
    if (lifetimeWageredUsdt >= t.minWageredUsdt) pick = t;
  }
  return pick;
}

export function nextTier(current: VipTier): VipTier | null {
  const idx = VIP_TIERS.findIndex(t => t.id === current.id);
  return idx >= 0 && idx < VIP_TIERS.length - 1 ? VIP_TIERS[idx + 1] : null;
}

/** Progress 0..1 from the start of `current` to the start of `next`. */
export function tierProgress(lifetimeWageredUsdt: number, current: VipTier, next: VipTier | null): number {
  if (!next) return 1;
  const span = next.minWageredUsdt - current.minWageredUsdt;
  if (span <= 0) return 1;
  return Math.max(0, Math.min(1, (lifetimeWageredUsdt - current.minWageredUsdt) / span));
}
